var app = require("express")();
var bodyParser = require("body-parser");
var auth = require("../lib/index.js");

app.use(bodyParser.json()); 

//	The url '/' can only be called if the request header will provide the token
//	generated by '/generate_token'
//	The client must submit the token via 'Authorization' in the HTTP header
//	E.g Authorization: [token]

auth.noTokenHandler = function(req, res) {
	res.status(403).send("This action is not allowed!");
}

app.get("/", auth.middleware(), function(req, res) {

	//	Refresh the token to avoid expiration
	res.refreshToken();

	//	Send the secret data to the client
	res.send(req.getTokenData());
});

//	Generate a token for the client
app.get("/generate_token", function(req, res) {

	//	The second parameter's object is stored server-side
	//	and can be used to hold sensible data.
	//	Tokens can be used to identify connections
	auth.generateAndSendToken(res, { secretData: "Hello world" });
});

app.listen(3000);